# Generated by Django 5.1.4 on 2025-04-22 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSampah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriArtikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankSampah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('jam_operasional', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gambar', models.ImageField(upload_to='bank_sampah/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_sampah', models.ManyToManyField(to='manajemen.jenissampah')),
            ],
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('konten', models.TextField()),
                ('gambar', models.ImageField(upload_to='artikel/')),
                ('tanggal_publikasi', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('dilihat', models.IntegerField(default=0)),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen.kategoriartikel')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=20)),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('bank_sampah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen.banksampah')),
                ('jenis_sampah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen.jenissampah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
