# Generated by Django 5.1.4 on 2025-12-24 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0002_jenissampah_kategoriartikel_banksampah_artikel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendaftaranAnggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('nik', models.CharField(max_length=16, unique=True, verbose_name='NIK')),
                ('nomor_telepon', models.CharField(max_length=15, verbose_name='Nomor Telepon/WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('alamat_lengkap', models.TextField(verbose_name='Alamat Lengkap')),
                ('rt_rw', models.CharField(max_length=10, verbose_name='RT/RW')),
                ('kelurahan', models.CharField(max_length=100, verbose_name='Kelurahan/Desa')),
                ('kecamatan', models.CharField(max_length=100, verbose_name='Kecamatan')),
                ('kota', models.CharField(max_length=100, verbose_name='Kota/Kabupaten')),
                ('kode_pos', models.CharField(max_length=6, verbose_name='Kode Pos')),
                ('estimasi_volume', models.CharField(help_text='Estimasi volume sampah per bulan (kg)', max_length=50, verbose_name='Estimasi Volume')),
                ('foto_ktp', models.ImageField(blank=True, null=True, upload_to='ktp_anggota/', verbose_name='Foto KTP')),
                ('alasan_bergabung', models.TextField(blank=True, verbose_name='Alasan Bergabung')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pendaftaran')),
                ('tanggal_disetujui', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Disetujui')),
                ('keterangan_admin', models.TextField(blank=True, help_text='Catatan dari admin', verbose_name='Keterangan Admin')),
                ('nomor_anggota', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Nomor Anggota')),
                ('bank_sampah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen.banksampah', verbose_name='Bank Sampah Terdekat')),
                ('jenis_sampah_disetor', models.ManyToManyField(blank=True, to='manajemen.jenissampah', verbose_name='Jenis Sampah yang Disetor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendaftaran Anggota',
                'verbose_name_plural': 'Pendaftaran Anggota',
                'ordering': ['-tanggal_daftar'],
            },
        ),
    ]
