# Generated by Django 5.1.4 on 2025-12-29 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_tracking', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Kode Tracking')),
                ('jenis_sampah', models.CharField(choices=[('plastik', 'Plastik'), ('kertas', 'Kertas'), ('logam', 'Logam'), ('kaca', 'Kaca'), ('organik', 'Organik'), ('elektronik', 'Elektronik'), ('campuran', 'Campuran')], max_length=20, verbose_name='Jenis Sampah')),
                ('berat_estimasi', models.DecimalField(decimal_places=2, help_text='Dalam kilogram (kg)', max_digits=6, verbose_name='Estimasi Berat')),
                ('berat_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Berat setelah ditimbang (kg)', max_digits=6, null=True, verbose_name='Berat Aktual')),
                ('alamat_jemput', models.TextField(verbose_name='Alamat Penjemputan')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Penjemputan'), ('picked', 'Sedang Dijemput'), ('transit', 'Dalam Perjalanan'), ('sorting', 'Sedang Dipilah'), ('processed', 'Sedang Diproses'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
                ('poin_didapat', models.IntegerField(default=0, verbose_name='Poin yang Didapat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('estimated_pickup', models.DateTimeField(blank=True, null=True, verbose_name='Estimasi Penjemputan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai Pada')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengiriman_ditangani', to=settings.AUTH_USER_MODEL, verbose_name='Petugas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengiriman_sampah', to=settings.AUTH_USER_MODEL, verbose_name='Pengirim')),
            ],
            options={
                'verbose_name': 'Pengiriman',
                'verbose_name_plural': 'Pengiriman',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PenjemputanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='Area/Kelurahan')),
                ('hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu'), ('minggu', 'Minggu')], max_length=10, verbose_name='Hari')),
                ('jam_mulai', models.TimeField(verbose_name='Jam Mulai')),
                ('jam_selesai', models.TimeField(verbose_name='Jam Selesai')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Petugas')),
            ],
            options={
                'verbose_name': 'Jadwal Penjemputan',
                'verbose_name_plural': 'Jadwal Penjemputan',
                'ordering': ['hari', 'jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Penjemputan'), ('picked', 'Sedang Dijemput'), ('transit', 'Dalam Perjalanan'), ('sorting', 'Sedang Dipilah'), ('processed', 'Sedang Diproses'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], max_length=20, verbose_name='Status')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('lokasi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokasi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracking.pengiriman', verbose_name='Pengiriman')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Petugas')),
            ],
            options={
                'verbose_name': 'History Tracking',
                'verbose_name_plural': 'History Tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pengiriman',
            index=models.Index(fields=['kode_tracking'], name='tracking_pe_kode_tr_7eb94a_idx'),
        ),
        migrations.AddIndex(
            model_name='pengiriman',
            index=models.Index(fields=['user', '-created_at'], name='tracking_pe_user_id_efb5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='pengiriman',
            index=models.Index(fields=['status'], name='tracking_pe_status_8f978b_idx'),
        ),
    ]
